server:
  port: 9090

topicos:
  notafiscal:
    request:
      topic: "notafiscal.request.topic.v1"

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://localhost:3306/notafiscal
    username: root
    password: P@55w0rd!My$3cr37
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${POOL_SIZE:25}
      connection-timeout: ${CONNECTION_TIMEOUT:60000}